global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker:8000', 'complex_worker:8000', 'simple_worker:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']


  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
