groups:
- name: sql-chat-alerts
  rules:
  - alert: HighDiskUsage
    expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage on {{ $labels.instance }}"
      description: "Disk usage is over 85% on {{ $labels.instance }} (current value: {{ $value }}%)"

  - alert: HighMemoryUsage
    expr: 100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is over 90% on {{ $labels.instance }} (current value: {{ $value }}%)"

  - alert: LLMAPIErrors
    expr: increase(errors_total[15m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High LLM API error rate"
      description: "More than 10 LLM API errors in the last 15 minutes (current value: {{ $value }})"

  - alert: SlowAPIResponse
    expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le)) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Slow API response time"
      description: "95th percentile of API response time is over 2 seconds (current value: {{ $value }}s)"