global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sql-chat-agent'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts/*.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape FastAPI applications
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'app1:8000'
          - 'app2:8000'
        labels:
          service: 'fastapi'

  # Scrape Celery workers (via Flower)
  - job_name: 'celery'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flower:5555']
        labels:
          service: 'celery'

  # Scrape Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'

  # Scrape PostgreSQL (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: 
          - 'postgres-nps:5432'
          - 'postgres-products:5432'
        labels:
          service: 'postgres'

  # Scrape Nginx (if nginx-prometheus-exporter is set up)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
        labels:
          service: 'nginx'
